# Generated by Django 5.2 on 2026-04-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, help_text='이 세션의 원본 지문 (OCR 결과)')),
                ('level', models.IntegerField(choices=[(1, 'Level 1 — 2자 단어 / 3.0s'), (2, 'Level 2 — 3자 단어 / 2.5s'), (3, 'Level 3 — 3자 단어 / 2.0s'), (4, 'Level 4 — 4자+ / 1.5s')], default=1)),
                ('cell_duration_sec', models.FloatField(default=2.0)),
                ('total_words', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('avg_response_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='세션 내 순번 (0-base)')),
                ('word', models.CharField(help_text='출제 단어', max_length=32)),
                ('braille_cells', models.JSONField(help_text='[[p1..p6], ...] 실제 출력된 점자 셀 배열')),
                ('user_answer', models.CharField(blank=True, max_length=64)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_ms', models.IntegerField(blank=True, help_text='출력 완료 시점~답변 수신까지 ms', null=True)),
                ('whisper_logprob', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='training.session')),
            ],
            options={
                'ordering': ['session', 'index'],
                'unique_together': {('session', 'index')},
            },
        ),
    ]
